{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fahclient.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "fahclient.fullname" . }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "fahclient.fullname" . }}-service
            port:
              number: {{ .Values.service.port }}
        pathType: ImplementationSpecific
        path: {{ .Values.ingress.path | default "/" }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
  {{- end }}
{{- end }}
