---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fahclient.fullname" . }}
spec:
{{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "fahclient.fullname" . }}
  serviceName: {{ include "fahclient.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ include "fahclient.fullname" . }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: 45
      initContainers:
      - name: init
        image: alpine:latest
        command: ['sh', '-c', "mkdir -p /fah && cp -f /tmp/fahclient/config.xml /fah/config.xml"]
        volumeMounts:
          - name: fah
            mountPath: /fah
          - name: fahclient-config
            mountPath: /tmp/fahclient/config.xml
            subPath: config.xml
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: PUID
            value: {{ .Values.securityContext.runAsUser | quote }}
          - name: PGID
            value: {{ .Values.securityContext.runAsGroup | quote }}
        lifecycle:
          preStop:
            exec:
              command: ["FAHClient", "--send-command", "shutdown"]
        ports:
        - containerPort: 7396
          name: http
        volumeMounts:
        - name: fah
          mountPath: /fah
        resources:
          {{- if .Values.fahClient.gpu.enabled }}
            limits:
              nvidia.com/gpu: 1
          {{ else }}
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: fahclient-config
          configMap:
            name: {{ include "fahclient.fullname" . }}-config
      {{- if .Values.fahClient.gpu.enabled }}
      nodeSelector:
        accelerator: {{ .Values.fahClient.gpu.accelerator }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: fah
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.storageClassName }}
      storageClassName: {{ .Values.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: 1Gi
