# Default values for fahclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: foldingathome/fah-gpu
  tag: latest
  pullPolicy: Always

# to use Vertical Pod Autoscaling install:
# https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
verticalPodAutoscaling:
  enabled: false
  # valid values are Auto, Recreate, Initial, Off
  updateMode: Auto

horizontalPodAutoscaling:
  enabled: false
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 90

fahClient:
  gpu:
    # beta feature
    enabled: false
    accelerator: nvidia-tesla-p100 # or nvidia-tesla-k80 etc.
  configXml: |
    <config>
      <!-- Set with your user, passkey, team-->
      <user value="Anonymous"/>
      <passkey value=""/>
      <team value="0"/>

      <power value="full"/>

      <web-enable v='false'/>
      <!-- Uncomment when using ingress: -->
      <!-- <allow v='127.0.0.1 10.0.0.0/8 192.168.0.0/16' />
      <web-allow v='127.0.0.1 10.0.0.0/8 192.168.0.0/16' /> -->

      <disable-viz v='true'/>
      <gui-enabled v='false'/>
      <!-- 1 slots for GPUs -->
      <!-- beta feature: uncomment the statement below if you have set
      fahClient.gpu.enabled to true -->
      <!-- <slot id='0' type='GPU'> </slot> -->
    </config>

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 9999
  runAsGroup: 9999
  fsGroup: 9999

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

# Don't forget to enable external access in configmap, to access service
service:
  type: ClusterIP
  port: 80

# Ingress for WebUI
# Don't forget to enable external access in configmap, too
ingress:
  enabled: false
  hostname: chart-example.local
  path: /

  # Enable TLS for Ingress e.g. letsencrypt using cert-manager
  tls: false

  # Ingress Annotations
  annotations:
    #cert-manager.io/cluster-issuer: cluster-issuer
    #kubernetes.io/ingress.class: nginx
    #ingress.kubernetes.io/ssl-redirect: 'true'

storageClassName: ""

# set to some sane defaults to prevent interference
# of your other workload.
resources:
  limits:
    cpu: 1.0
    memory: 256Mi
  requests:
    cpu: 1.0
    memory: 128Mi
