# Default values for fahclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: johnktims/folding-at-home
  tag: latest
  pullPolicy: IfNotPresent

# to use Vertical Pod Autoscaling install:
# https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
verticalPodAutoscaling:
  enabled: false
  # valid values are Auto, Recreate, Initial, Off
  # https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
  updateMode: Auto

horizontalPodAutoscaling:
  enabled: false
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 90

fahClient:
  user: Anonymous
  team: 0
  smp: true
  power: full
  # remove {} and uncomment/add arguments as "- --arg=value"
  extraArgs: {}
    #- --client-threads=1
    #- --passkey=bcddf917c5b90f22c3cf6288699b2a005e2350289a44
    #- --chdir=/some/other/workdir

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  fsGroup: 9999

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false 
  runAsNonRoot: true
  runAsUser: 9999

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# set to some sane defaults to prevent interference
# of your other workload.
resources:
  limits:
    cpu: 1.0
    memory: 256Mi
  requests:
    cpu: 1.0
    memory: 128Mi
