# Default values for fahclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: foldingathome/fah-gpu
  tag: latest
  pullPolicy: Always

# to use Vertical Pod Autoscaling install:
# https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
verticalPodAutoscaling:
  enabled: false
  # valid values are Auto, Recreate, Initial, Off
  updateMode: Auto

horizontalPodAutoscaling:
  enabled: false
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 90

fahClient:
  gpu:
    # beta feature
    enabled: false
    accelerator: nvidia-tesla-p100 # or nvidia-tesla-k80 etc.
  configXml: |
    <config>
      <!-- Set with your user, passkey, team-->
      <user value="Anonymous"/>
      <passkey value=""/>
      <team value="0"/>

      <power value="full"/>

      <web-enable v='false'/>
      <disable-viz v='true'/>
      <gui-enabled v='false'/>
      <!-- 1 slots for GPUs -->
      <!-- beta feature: uncomment the statement below if you have set
      fahClient.gpu.enabled to true -->
      <!-- <slot id='0' type='GPU'> </slot> -->
    </config>

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false 
  runAsNonRoot: true
  runAsUser: 9999
  runAsGroup: 9999

service:
  type: ClusterIP
  port: 80

storageClassName: ""

# set to some sane defaults to prevent interference
# of your other workload.
resources:
  limits:
    cpu: 1.0
    memory: 256Mi
  requests:
    cpu: 1.0
    memory: 128Mi
